authentication/urls.py
from django.urls import path, include
from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('login/', views.login_view_js),
    path('logout/', views.logout_view, name='logout'),
    path('logoutJS/', views.logout_view_js, name="logoutJS"),

    path('register/', views.register),
    path('register/cancel/', views.cancelRegistration),
    path('register/resend/', views.resendVerificationCode),
    path('register/verify/', views.verifyRegistration),

    path('recover/', views.recover),
    path('recover/cancel/', views.cancelRecovery),
    path('recover/resend/', views.resendRecoveryCode),
    path('recover/verify/', views.verifyRecovery),
    path('recover/changepassword/', views.changepassword),

    path('<str:username>/', views.account, name='account'),
    path('<str:username>/details/', views.details),
    path('<str:username>/details/edit/', views.editDetails),
    path('<str:username>/details/edit/check/', views.emailsecuritycheck),
    path('<str:username>/details/edit/check/confirm/', views.emailsecurityconfirm),
    path('<str:username>/details/edit/check/email/', views.checkemail),
    path('<str:username>/details/edit/check/email/resend/', views.reconfirmCheckemail),
    path('<str:username>/details/edit/check/email/cancel/', views.cancelCheckemail),
    path('<str:username>/details/edit/check/email/change/', views.changeEmail),
    path('<str:username>/details/edit/change/password/', views.changePassword),
]

authentication/templates/authentication/header.html
<header id="auhsiteheader">
<nav class="navbar navbar-expand-md navbar-light bg-white text-dark sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="/" data-bs-toggle="tooltip" data-bs-placement="right" title="Homepage">
            <i class="bi bi-house text-dark fs-5"></i>
            <span class="badge rounded-pill bg-dark text-white fs-5">{{SITE_TITLE}}</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#authSiteHeaderNavBar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="authSiteHeaderNavBar">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#recoverModal"><span>Recover</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#registerModal"><span>Register</span></a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#changePasswordModal"><span>Change Password</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authentication:logout' %}"><span>Logout</span></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
</header>

authentication/templates/authentication/home_modals.html
<!-------------------------------------------------------------------------------------------------------------->
<!-- Edit Profile Modal -->
<div class="modal fade" id="editProfileModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="editProfileModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content bg-white text-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="editProfileModalLabel">Edit Profile</h5>
                <button type="button" class="btn-close auth-btn" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="editProfileForm-modalBody"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark auth-btn btn-sm" data-bs-dismiss="modal" id="editProfileModalBtnClose">Close</button>
                <button type="submit" form="editProfileForm" class="btn btn-outline-dark auth-btn btn-sm">
                    Save changes
                    <span class="spinner-border spinner-border-sm auth-spinner" role="status" aria-hidden="true" hidden></span>
                </button>
            </div>
        </div>
    </div>
</div>
<!-- Edit Profile Modal Hndlebars -->
<script id="EditProfileFormHandlebars" type="text/x-handlebars-template">
    {% verbatim %}
    <form class="row g-3" id="editProfileForm" onsubmit="edit_profile(event, '{{username}}');">
        <div class="col-md-6">
            <label for="inputFirstName" class="form-label">First Name</label>
            <input type="text" class="form-control" id="inputFirstName" value="{{first_name}}">
        </div>
        <div class="col-md-6">
            <label for="inputLastName" class="form-label">Last Name</label>
            <input type="text" class="form-control" id="inputLastName" value="{{last_name}}">
        </div>
        <div class="col-md-6">
            <label for="inputUsername" class="form-label">Username</label>
            <input type="text" class="form-control" id="inputUsername" value="{{username}}">
        </div>
        <div class="col-md-6">
            <label for="inputEmail" class="form-label">Email Address</label>
            <input type="email" class="form-control" id="inputEmail" value="{{email}}" disabled>
        </div>
    </form>
    <div class="errormessage" id="edit_profile_error"><br></div>
    {% endverbatim %}
</script>
<!-------------------------------------------------------------------------------------------------------------->


<!-------------------------------------------------------------------------------------------------------------->
<!-- Confirm Password Modal -->
<div class="modal fade" id="confirmPasswordModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="confirmPasswordModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content  bg-white text-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmPasswordModalLabel">Confirm Password</h5>
                <button type="button" class="btn-close auth-btn" data-bs-dismiss="modal" id="confirmPasswordModalBtnClose" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="confirmPasswordForm-modalBody"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark auth-btn btn-sm" data-bs-dismiss="modal" onclick="cancelprocesses();">Cancel</button>
                <button type="submit" form="confirmPasswordForm" class="btn btn-outline-dark auth-btn btn-sm">
                    Confirm
                    <span class="spinner-border spinner-border-sm auth-spinner" role="status" aria-hidden="true" hidden></span>
                </button>
            </div>
        </div>
    </div>
</div><!-- Confirm Password Modal Handlebars -->
<script id="confirmPasswordFormHandlebars" type="text/x-handlebars-template">
    {% verbatim %}
    <form class="row g-3" id="confirmPasswordForm" onsubmit="confirmPassword(event, '{{username}}');">
        <div class="col-md-12">
            <label for="inputUsername1" class="form-label">Username</label>
            <input type="text" class="form-control form-control-sm" id="inputUsername1" value="{{username}}" disabled>
        </div>
        <div class="col-md-12">
            <label for="inputPassword" class="form-label">Password</label>
            <input type="password" class="form-control form-control-sm" id="inputPassword">
        </div>
    </form>
    <div class="errormessage" id="confirm_password_error"><br></div>
    {% endverbatim %}
</script>
<!-------------------------------------------------------------------------------------------------------------->


<!-------------------------------------------------------------------------------------------------------------->
<!-- Change Email Form Modal -->
<div class="modal fade" id="changeEmailFormModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="changeEmailFormModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content bg-white text-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="changeEmailFormModalLabel">Change Email</h5>
                <button type="button" class="btn-close auth-btn" data-bs-dismiss="modal" id="changeEmailModalBtnClose" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="changeEmailFormDiv"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark auth-btn btn-sm" data-bs-dismiss="modal" onclick="cancelprocesses();">Cancel</button>
                <button type="submit" form="changeEmailForm" class="btn btn-outline-dark auth-btn btn-sm">
                    Continue
                    <span class="spinner-border spinner-border-sm auth-spinner" role="status" aria-hidden="true" hidden></span>
                </button>
            </div>
        </div>
    </div>
</div>
<!-- Change Email Form Modal Handlebars -->
<script id="changeEmailFormHandlebars" type="text/x-handlebars-template">
    {% verbatim %}
        <form class="row g-3" id="changeEmailForm" onsubmit="changeEmail(event, '{{username}}');">
            <div class="col-md-12">
                <label for="inputEmail_current" class="form-label">Current Email Address</label>
                <input type="email" class="form-control form-control-sm" id="inputEmail_current" value="{{email}}" disabled>
            </div>
            <div class="col-md-12">
                <label for="inputEmail_new" class="form-label">New Email Address</label>
                <input type="email" class="form-control form-control-sm" id="inputEmail_new">
            </div>
        </form>
        <div class="errormessage" id="change_email_error"><br></div>
    {% endverbatim %}
</script>
<!-------------------------------------------------------------------------------------------------------------->


<!-------------------------------------------------------------------------------------------------------------->
<!-- Verify Password Recovery Modal -->
<div class="modal fade" id="verifyRecoveryModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="verifyRecoveryModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content bg-white text-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="verifyRecoveryModalLabel">Verify Your Email Address</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" disabled id="closeVerifyRecoveryFormBtn"></button>
            </div>
            <div class="modal-body text-center" id="verifyChangeEmailFormDiv"></div>
            <div class="modal-footer">
                <div class="btn-group w-100">
                    <button type="button" class="btn btn-sm btn-outline-dark w-25 auth-btn" onclick="cancelVerifyRecovery('{{request.user.username}}');" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" form="verifyRecoveryForm" class="btn btn-sm btn-outline-dark w-25 auth-btn">
                        Verify
                        <span class="spinner-border spinner-border-sm auth-spinner" role="status" aria-hidden="true" hidden></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Verify Password Recovery Modal Handlbars -->
<script id="verifyChangeEmailFormHandlebars" type="text/x-handlebars-template">
    {% verbatim %}
    <div class="errormessage" id="verifyRecoveryError"><br></div>
    <h6>{{new_email}}</h6>
    <form class="mb-3" id="verifyRecoveryForm" onsubmit="verifyRecovery(event, '{{username}}');">
        <div class="mb-3">
            <label for="verifyRecoveryFormCode" class="form-label"><span class="requirement">*</span>Verification Code</label>
            <input type="text" class="form-control form-control-sm" id="verifyRecoveryFormCode" placeholder="Verification Code" aria-describedby="VerifyRegisterHelp">
            <div id="VerifyRegisterHelp" class="form-text text-dark">Check your Inbox/Spam folder for the verification code.</div>
        </div>
    </form>
    <a href="" class="hover auth-link" onclick="resendVerificationCodeRecovery(event, '{{username}}');">Resend verification Code</a>
    {% endverbatim %}
</script>
<!-------------------------------------------------------------------------------------------------------------->


<!-------------------------------------------------------------------------------------------------------------->
<!-- Change Password Modal -->
<div class="modal fade" id="changePasswordModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="changePasswordModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content  bg-white text-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="changePasswordModalLabel">Change Password</h5>
                <button type="button" class="btn-close auth-btn" data-bs-dismiss="modal" id="changePasswordModalBtnClose" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form class="row g-3" id="changePasswordForm" onsubmit="changepassword(event, '{{request.user.username}}');">
                    <div class="col-md-12">
                        <label for="username_change_password" class="form-label"><span class="requirement">*</span>Username</label>
                        <input type="text" class="form-control form-control-sm" id="username_change_password" value="{{request.user.username}}" disabled>
                    </div>
                    <div class="col-md-12">
                        <label for="currentpassword" class="form-label"><span class="requirement">*</span>Current Password</label>
                        <input type="password" class="form-control form-control-sm" id="currentpassword" placeholder="Current Password">
                    </div>
                    <div class="col-md-12">
                        <label for="newpassword1" class="form-label"><span class="requirement">*</span>New Password</label>
                        <input type="password" class="form-control form-control-sm" id="newpassword1" placeholder="New Password" aria-describedby="recoverPassword1Help">
                        <div id="recoverPassword1Help" class="form-text text-dark">Between 8 to 20 characters.</div>
                    </div>
                    <div class="col-md-12">
                        <label for="newpassword2" class="form-label"><span class="requirement">*</span>Confirm New Password</label>
                        <input type="password" class="form-control form-control-sm" id="newpassword2" placeholder="Confirm New Password" aria-describedby="recoverPassword2Help">
                        <div id="recoverPassword2Help" class="form-text text-dark">Must include an alphabet, a digit and a special character.</div>
                    </div>
                </form>
                <div class="errormessage" id="change_password_error"><br></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark auth-btn btn-sm" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" form="changePasswordForm" class="btn btn-outline-dark auth-btn btn-sm">
                    Update
                    <span class="spinner-border spinner-border-sm auth-spinner" role="status" aria-hidden="true" hidden></span>
                </button>
            </div>
        </div>
    </div>
</div>
<!-- Password Change Successful Modal -->
<div class="modal fade" id="pswdChngSuccessMsg" tabindex="-1" aria-labelledby="pswdChngSuccessMsgLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content bg-white text-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="pswdChngSuccessMsgLabel">Success</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                You have successfully changed your password.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark btn-sm" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-------------------------------------------------------------------------------------------------------------->

authentication/templates/authentication/homepage.html
{% extends 'authentication/layout.html' %}


{% load static %}

{% block style %}{% endblock %}
{% block title %}My Account{% endblock %}


{% block body %}
<div class="container mt-3 text-center">
    <div class="row" id="personDetailsDiv"></div>
    {% include 'authentication/home_modals.html' with request=request %}
    <div class="btn-group" style="display: none;">
        <!-- Edit Profile Button trigger modal -->
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#editProfileModal" id="editProfileModalBtn" hidden>
            Edit Profile
        </button>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmPasswordModal" id="confirmPasswordModalBtn" hidden>
            Confirm Password
        </button>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#changeEmailFormModal" id="changeEmailFormModalBtn" hidden>
            Change Email
        </button>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#verifyRecoveryModal" id="verifyRecoveryFormModalBtn" hidden>
            Verify Register
        </button>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#pswdChngSuccessMsg" id="pswdChngSuccessMsgBtn" hidden>
            password change success
        </button>
    </div>
</div>
{% endblock %}


{% block static %}
<script src="{% static 'authentication/js/homepage.js' %}"></script>
<script id="PersonDetailsHandlebars" type="text/x-handlebars-template">
    {% verbatim %}
    <div class="col-12">
        <div style="text-align: start;">
            <h5>
                Your Profile
                <a href="" class="text-decoration-none" onclick="editprofile(event, '{{username}}');">
                    <i class="bi bi-pencil-fill text-primary fs-5"></i>
                </a>
            </h5>
        </div>
        <hr>
        <div class="row fs-4">
            <div class="col-sm-4">First Name</div>
            <div class="col-sm-8">{{first_name}}</div>
            <hr>
            <div class="col-sm-4">Last Name</div>
            <div class="col-sm-8">{{last_name}}</div>
            <hr>
            <div class="col-sm-4">Username</div>
            <div class="col-sm-8" id="username">{{username}}</div>
            <hr>
            <div class="col-sm-4">Email</div>
            <div class="col-sm-8">
                {{email}}
                <a href="" class="text-decoration-none" onclick="editProfileEmail(event, '{{username}}');">
                    <i class="bi bi-pencil-fill text-primary fs-5"></i>
                </a>
            </div>
            <hr>
        </div>
    </div>
    {% endverbatim %}
</script>
{% endblock %}

authentication/templates/authentication/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if FAVICON %}
    <link rel="icon" href="{% static 'authentication/favicon_io/favicon.ico' %}" type = "image/x-icon">
    {% endif %}

    <link href="{% static 'authentication/assets/node_modules/bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'authentication/assets/node_modules/bootstrap-icons/font/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'authentication/css/layout.css' %}" rel="stylesheet">
    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="p-1 m-1">
    {% include 'authentication/header.html' with request=request SITE_TITLE=SITE_TITLE %}
    {% block body %}{% endblock %}
    <script src="{% static 'authentication/assets/node_modules/bootstrap/dist/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'authentication/assets/node_modules/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'authentication/assets/node_modules/handlebars/dist/handlebars.js' %}"></script>
    <script>
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })
    </script>
    <!--Script for popovers-->
    <script>
        var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
        var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
            return new bootstrap.Popover(popoverTriggerEl)
        })
    </script>
    {% block static %}{% endblock %}
</body>
</html>

authentication/templates/authentication/login.html
{% extends 'authentication/layout.html' %}
{% load static %}

{% block style %}{% endblock %}
{% block title %}Login{% endblock %}


{% block body %}
{% include 'authentication/auth_modals.html' %}
<div class="container">
    <div class="row mt-5 text-center">
        <div class="col-xl-4 col-lg-3 col-md-2 col-1"></div>
        <div class="col-xl-4 col-lg-6 col-md-8 col-10">
            <div class="card text-center border-0 bg-white text-dark" style="width: 100%;">
                <div class="card-body">
                    <h4 class="card-title">Login</h4>
                    <h6 class="card-subtitle mb-2" style="color: red;">
                        {% if login_error %}
                        {{login_error}}
                        {% else %}
                        <br>
                        {% endif %}
                    </h6>
                    <form class="card-text mb-3" action="" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="loginFormUsername" class="form-label"><span class="requirement">*</span>Username / Email Address</label>
                            <input type="text" class="form-control" id="loginFormUsername" name="username" placeholder="Username or Email Address" autofocus>
                        </div>
                        <div class="mb-3">
                            <label for="loginFormPassword" class="form-label"><span class="requirement">*</span>Password</label>
                            <input type="password" class="form-control" id="loginFormPassword" name="password" placeholder="Password">
                        </div>
                        <button type="submit" class="btn btn-outline-dark w-100">Login</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-xl-4 col-lg-3 col-md-2 col-1"></div>
    </div>
</div>
{% endblock %}


{% block static %}
<script src="{% static 'authentication/js/login.js' %}"></script>
{% endblock %}